# [tool.commitizen]
# name = "cz_conventional_commits"
# tag_format = "$version"
# version_scheme = "semver"
# version = "0.0.1"
# update_changelog_on_bump = true
# major_version_zero = true

[tool.commitizen]
name = "cz_customize"
tag_format = "snrd/v$version"
ignored_tag_formats = ["*/v${version}", "v${version}"]
version_scheme = "semver"
version_provider = "scm"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
major_version_zero = true
annotated_tag = true
pre_bump_hooks = ["bash scripts/hook-bump-pre.sh"]
post_bump_hooks = ["goreleaser release --clean -f cmd/snrd/.goreleaser.yml"]

[tool.commitizen.customize]
bump_pattern = "^(feat|fix|refactor|perf|BREAKING CHANGE)"
bump_map = { "BREAKING CHANGE" = "MAJOR", "feat" = "MINOR", "fix" = "PATCH", "refactor" = "PATCH", "perf" = "PATCH" }
default_bump = "PATCH"
changelog_pattern = "^(feat|fix|refactor|docs|build)\\(core\\)(!)?:"
