customCommands:
  - key: "C"
    command: |
      git commit -m "{{ .Form.Type }}{{if .Form.Scopes}}({{ .Form.Scopes }}){{end}}{{if .Form.BreakingChange}}!{{end}}: {{ .Form.Description }}" \
      {{- if .Form.LongDescription }}
      -m "{{ .Form.LongDescription }}" \
      {{- end }}
      {{- if .Form.BreakingChange }}
      -m "BREAKING CHANGE: {{ .Form.BreakingChange }}"
      {{- end }}
    description: "commit with conventional commits"
    context: "files"
    prompts:
      - type: "menu"
        title: "Select the type of change you are committing."
        key: "Type"
        options:
          - name: "Feature"
            value: "feat"
          - name: "Fix"
            value: "fix"
          - name: "Documentation"
            value: "docs"
          - name: "Styles"
            value: "style"
          - name: "Refactor"
            value: "refactor"
          - name: "Performance"
            value: "perf"
          - name: "Tests"
            value: "test"
          - name: "Build"
            value: "build"
          - name: "CI"
            value: "ci"
          - name: "Chore"
            value: "chore"
          - name: "Revert"
            value: "revert"
      - type: "input"
        title: "Scope (optional)"
        key: "Scopes"
      - type: "input"
        title: "Short description"
        key: "Description"
      - type: "input"
        title: "Long description (optional)"
        key: "LongDescription"
      - type: "input"
        title: "Breaking change description (leave empty if none)"
        key: "BreakingChange"
      - type: "confirm"
        title: "Is the commit message correct?"
